name: Respond to Trigger

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v2

      - name: Perform actions in target repository
        run: |
          # Your commands here, for example:
          echo "Triggered by source repository"
          # Add your commands to commit and push changes if needed
